on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform format syntax
        id: fmt
        run: terraform fmt -write=true -recursive
      
      - name: Terraform init
        run: |
          ls -lthr

