on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  terraform:
    name: Terraform reusable deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository (caller)
        uses: actions/checkout@v3

      - name: Checkout repository (called)
        uses: actions/checkout@v3
        with:
          repository: 'lbrealdev/terraform-aws-lambda'
          path: 'module'

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      
      - name: Test command
        run: |
          cd ..
          ls -lthr
          echo ${{ inputs.config-path }}

      - name: Terraform init (test)
        id: init
        run: terraform init
        working-directory: module

      - name: Terraform format syntax
        id: fmt
        run: terraform fmt -write=true -recursive
        working-directory: module

      - name: Terraform plan
        id: plan
        run: ls -lthr *.tf
        working-directory: module

