on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  terraform:
    name: Terraform reusable deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository (caller)
        uses: actions/checkout@v3

      - name: Checkout repository (called)
        uses: actions/checkout@v3
        with:
          repository: 'lbrealdev/terraform-aws-lambda'
          path: 'module'

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform format syntax
        id: fmt
        run: terraform fmt -write=true -recursive
      
      - name: Terraform init
        run: |
          cd ..
          ls -lthr

      - name: Terraform plan (test)
        id: plan
        run: terraform plan

