name: Terraform module for AWS lambda function
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

env:
  TERRAFORM_MODULE_DIR: terraform-module
  TERRAFORM_MODULE_WORKFLOW: lbrealdev/terraform-aws-lambda
  TERRAFORM_VERSION: 1.3.0
  
jobs:
  terraform:
    name: Terraform lambda function
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_MODULE_DIR }}

    steps:
      - name: Checkout repository (caller)
        uses: actions/checkout@v3

      - name: Checkout repository (called)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TERRAFORM_MODULE_WORKFLOW }}
          path: ${{ env.TERRAFORM_MODULE_DIR }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan -out plan

      - name: Test command
        run: |
          ls -lthr $GITHUB_WORKSPACE
          pwd
